### ISSUE TITLE
snapshot images from tutorials don't show up for me

### ISSUE THREAD

**Issue by durraniu** [sisl/AutomotiveVisualization.jl#12]
I am running the basics tutorial code in REPL. The tutorial shows the `snapshot` image. But when I run the code, I get:  

```
snapshot = render([roadway, scene], canvas_height=120)
Cairo.CairoSurfaceIOStream{UInt32}(Ptr{Nothing} @0x000000001b761f10, 1000.0, 120.0, IOBuffer(data=UInt8[...], readable=true, writable=true, seekable=true, append=false, size=0, maxsize=Inf, ptr=1, mark=-1))
```
Image is not generated. I am new to julia, so I don't know what I'm missing here. Please let me know how to view the resulting `snapshot`? Thank you.

**Comment by MaximeBouton** [comment]
Hi! I think you need to write the snapshot to a file to visualize it e.g.
```
write("empty_roadway_whitebg.svg", snapshot) 
```

If you run in a notebook or in the vscode extension, the rendering should be automatic I believe

**Comment by durraniu** [comment]
Thanks, it does work in vscode.
